### ISSUE TITLE
Not support for PHP 8.0

### ISSUE THREAD

**Issue by jahhernandez** [REBELinBLUE/laravel5-zxcvbn#11]
Hello are you planning on supporting PHP 8 as the version of bjeavons/zxcvbn-php you need has been upgrade to support PHP 8.0 on version 1.2 could you make the update to allow it?

**Comment by REBELinBLUE** [comment]
Hey, I am happy to accept a PR to add PHP 8 support, otherwise, I shall try and take a look at the weekend.

**Comment by REBELinBLUE** [comment]
Thanks, I've merged your PR
